[package]
name = "tasks_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anathema = {git = "https://github.com/togglebyte/anathema/", branch = "dev"}
tasks_core.workspace = true
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
